// src\resources\icons.ts
import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
  HiOutlineChartBar,
  HiOutlineChartPie,
  HiOutlineLockClosed,
  HiOutlineCube,
  HiOutlineServerStack,
  HiOutlineCog6Tooth,
  HiOutlineWrenchScrewdriver,
  HiOutlineQrCode,
  HiOutlineCircleStack,
  HiOutlineSquares2X2,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiReact,
  SiTypescript,
  SiNodedotjs,
  SiExpress,
  SiMongodb,
  SiMongoose,
  SiPostgresql,
  SiPrisma,
  SiDrizzle,
  SiSocketdotio,
  SiJsonwebtokens,
  SiFirebase,
  SiCloudinary,
  SiAxios,
  SiTailwindcss,
  SiDaisyui,
  SiReactquery,
  SiFramer,
  SiGit,
  SiVercel,
} from "react-icons/si";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaInstagram, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  // stack icons used by the skills and project sections in content.tsx
  react: SiReact,
  typescript: SiTypescript,
  nodejs: SiNodedotjs,
  express: SiExpress,
  mongodb: SiMongodb,
  mongoose: SiMongoose,
  postgresql: SiPostgresql,
  prisma: SiPrisma,
  drizzle: SiDrizzle,
  socketio: SiSocketdotio,
  jwt: SiJsonwebtokens,
  // NextAuth has no brand icon in react-icons; a lock stands in for it
  nextauth: HiOutlineLockClosed,
  firebase: SiFirebase,
  cloudinary: SiCloudinary,
  axios: SiAxios,
  tailwind: SiTailwindcss,
  daisyui: SiDaisyui,
  reactquery: SiReactquery,
  // Recharts has no brand icon in react-icons; a chart stands in for it
  recharts: HiOutlineChartBar,
  framer: SiFramer,
  git: SiGit,
  vercel: SiVercel,
  // generic icons for the ERP/manufacturing domain tags
  erp: HiOutlineCube,
  modules: HiOutlineSquares2X2,
  manufacturing: HiOutlineCog6Tooth,
  maintenance: HiOutlineWrenchScrewdriver,
  barcode: HiOutlineQrCode,
  database: HiOutlineCircleStack,
  server: HiOutlineServerStack,
  chart: HiOutlineChartPie,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
